package com.flycode.yearaccount.entity;

public class TabYearAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.ID
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.mID
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Integer mID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.collectYear
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private String collectYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.JanNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double janNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.FebNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double febNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.MarNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double marNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.AprNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double aprNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.MayNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double mayNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.JunNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double junNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.JulNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double julNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.AugNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double augNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.SepNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double sepNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.OctNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double octNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.NovNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double novNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.DecNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private Double decNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_YearAccount.infoID
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    private String infoID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.ID
     *
     * @return the value of tab_YearAccount.ID
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.ID
     *
     * @param ID the value for tab_YearAccount.ID
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.mID
     *
     * @return the value of tab_YearAccount.mID
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Integer getmID() {
        return mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.mID
     *
     * @param mID the value for tab_YearAccount.mID
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setmID(Integer mID) {
        this.mID = mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.collectYear
     *
     * @return the value of tab_YearAccount.collectYear
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public String getCollectYear() {
        return collectYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.collectYear
     *
     * @param collectYear the value for tab_YearAccount.collectYear
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setCollectYear(String collectYear) {
        this.collectYear = collectYear == null ? null : collectYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.JanNumber
     *
     * @return the value of tab_YearAccount.JanNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getJanNumber() {
        return janNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.JanNumber
     *
     * @param janNumber the value for tab_YearAccount.JanNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setJanNumber(Double janNumber) {
        this.janNumber = janNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.FebNumber
     *
     * @return the value of tab_YearAccount.FebNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getFebNumber() {
        return febNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.FebNumber
     *
     * @param febNumber the value for tab_YearAccount.FebNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setFebNumber(Double febNumber) {
        this.febNumber = febNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.MarNumber
     *
     * @return the value of tab_YearAccount.MarNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getMarNumber() {
        return marNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.MarNumber
     *
     * @param marNumber the value for tab_YearAccount.MarNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setMarNumber(Double marNumber) {
        this.marNumber = marNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.AprNumber
     *
     * @return the value of tab_YearAccount.AprNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getAprNumber() {
        return aprNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.AprNumber
     *
     * @param aprNumber the value for tab_YearAccount.AprNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setAprNumber(Double aprNumber) {
        this.aprNumber = aprNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.MayNumber
     *
     * @return the value of tab_YearAccount.MayNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getMayNumber() {
        return mayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.MayNumber
     *
     * @param mayNumber the value for tab_YearAccount.MayNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setMayNumber(Double mayNumber) {
        this.mayNumber = mayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.JunNumber
     *
     * @return the value of tab_YearAccount.JunNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getJunNumber() {
        return junNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.JunNumber
     *
     * @param junNumber the value for tab_YearAccount.JunNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setJunNumber(Double junNumber) {
        this.junNumber = junNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.JulNumber
     *
     * @return the value of tab_YearAccount.JulNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getJulNumber() {
        return julNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.JulNumber
     *
     * @param julNumber the value for tab_YearAccount.JulNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setJulNumber(Double julNumber) {
        this.julNumber = julNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.AugNumber
     *
     * @return the value of tab_YearAccount.AugNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getAugNumber() {
        return augNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.AugNumber
     *
     * @param augNumber the value for tab_YearAccount.AugNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setAugNumber(Double augNumber) {
        this.augNumber = augNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.SepNumber
     *
     * @return the value of tab_YearAccount.SepNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getSepNumber() {
        return sepNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.SepNumber
     *
     * @param sepNumber the value for tab_YearAccount.SepNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setSepNumber(Double sepNumber) {
        this.sepNumber = sepNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.OctNumber
     *
     * @return the value of tab_YearAccount.OctNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getOctNumber() {
        return octNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.OctNumber
     *
     * @param octNumber the value for tab_YearAccount.OctNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setOctNumber(Double octNumber) {
        this.octNumber = octNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.NovNumber
     *
     * @return the value of tab_YearAccount.NovNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getNovNumber() {
        return novNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.NovNumber
     *
     * @param novNumber the value for tab_YearAccount.NovNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setNovNumber(Double novNumber) {
        this.novNumber = novNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.DecNumber
     *
     * @return the value of tab_YearAccount.DecNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public Double getDecNumber() {
        return decNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.DecNumber
     *
     * @param decNumber the value for tab_YearAccount.DecNumber
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setDecNumber(Double decNumber) {
        this.decNumber = decNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_YearAccount.infoID
     *
     * @return the value of tab_YearAccount.infoID
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public String getInfoID() {
        return infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_YearAccount.infoID
     *
     * @param infoID the value for tab_YearAccount.infoID
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    public void setInfoID(String infoID) {
        this.infoID = infoID == null ? null : infoID.trim();
    }
}