package com.flycode.yearaccount.mapper;

import com.flycode.yearaccount.entity.TabYearAccount;
import com.flycode.yearaccount.entity.TabYearAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabYearAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_YearAccount
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    int countByExample(TabYearAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_YearAccount
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    int deleteByExample(TabYearAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_YearAccount
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    int insert(TabYearAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_YearAccount
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    int insertSelective(TabYearAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_YearAccount
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    List<TabYearAccount> selectByExample(TabYearAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_YearAccount
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") TabYearAccount record, @Param("example") TabYearAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_YearAccount
     *
     * @mbggenerated Thu Nov 12 12:52:33 CST 2015
     */
    int updateByExample(@Param("record") TabYearAccount record, @Param("example") TabYearAccountExample example);
}