package com.flycode.monthaccount.mapper;

import com.flycode.monthaccount.entity.TabMonthAccount;
import com.flycode.monthaccount.entity.TabMonthAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabMonthAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    int countByExample(TabMonthAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    int deleteByExample(TabMonthAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    int insert(TabMonthAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    int insertSelective(TabMonthAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    List<TabMonthAccount> selectByExample(TabMonthAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    int updateByExampleSelective(@Param("record") TabMonthAccount record, @Param("example") TabMonthAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    int updateByExample(@Param("record") TabMonthAccount record, @Param("example") TabMonthAccountExample example);
}