package com.flycode.dayaccount.entity;

import java.util.ArrayList;
import java.util.List;

public class TabDayAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    protected List<Criteria> oredCriteria;
    
    protected String tableName;

    public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public TabDayAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInfoIDIsNull() {
            addCriterion("infoID is null");
            return (Criteria) this;
        }

        public Criteria andInfoIDIsNotNull() {
            addCriterion("infoID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIDEqualTo(Integer value) {
            addCriterion("infoID =", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDNotEqualTo(Integer value) {
            addCriterion("infoID <>", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDGreaterThan(Integer value) {
            addCriterion("infoID >", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("infoID >=", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDLessThan(Integer value) {
            addCriterion("infoID <", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDLessThanOrEqualTo(Integer value) {
            addCriterion("infoID <=", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDIn(List<Integer> values) {
            addCriterion("infoID in", values, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDNotIn(List<Integer> values) {
            addCriterion("infoID not in", values, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDBetween(Integer value1, Integer value2) {
            addCriterion("infoID between", value1, value2, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDNotBetween(Integer value1, Integer value2) {
            addCriterion("infoID not between", value1, value2, "infoID");
            return (Criteria) this;
        }

        public Criteria andCollectDayIsNull() {
            addCriterion("collectDay is null");
            return (Criteria) this;
        }

        public Criteria andCollectDayIsNotNull() {
            addCriterion("collectDay is not null");
            return (Criteria) this;
        }

        public Criteria andCollectDayEqualTo(String value) {
            addCriterion("collectDay =", value, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayNotEqualTo(String value) {
            addCriterion("collectDay <>", value, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayGreaterThan(String value) {
            addCriterion("collectDay >", value, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayGreaterThanOrEqualTo(String value) {
            addCriterion("collectDay >=", value, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayLessThan(String value) {
            addCriterion("collectDay <", value, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayLessThanOrEqualTo(String value) {
            addCriterion("collectDay <=", value, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayLike(String value) {
            addCriterion("collectDay like", value, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayNotLike(String value) {
            addCriterion("collectDay not like", value, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayIn(List<String> values) {
            addCriterion("collectDay in", values, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayNotIn(List<String> values) {
            addCriterion("collectDay not in", values, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayBetween(String value1, String value2) {
            addCriterion("collectDay between", value1, value2, "collectDay");
            return (Criteria) this;
        }

        public Criteria andCollectDayNotBetween(String value1, String value2) {
            addCriterion("collectDay not between", value1, value2, "collectDay");
            return (Criteria) this;
        }

        public Criteria andMIDIsNull() {
            addCriterion("mID is null");
            return (Criteria) this;
        }

        public Criteria andMIDIsNotNull() {
            addCriterion("mID is not null");
            return (Criteria) this;
        }

        public Criteria andMIDEqualTo(Integer value) {
            addCriterion("mID =", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDNotEqualTo(Integer value) {
            addCriterion("mID <>", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDGreaterThan(Integer value) {
            addCriterion("mID >", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("mID >=", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDLessThan(Integer value) {
            addCriterion("mID <", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDLessThanOrEqualTo(Integer value) {
            addCriterion("mID <=", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDIn(List<Integer> values) {
            addCriterion("mID in", values, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDNotIn(List<Integer> values) {
            addCriterion("mID not in", values, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDBetween(Integer value1, Integer value2) {
            addCriterion("mID between", value1, value2, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDNotBetween(Integer value1, Integer value2) {
            addCriterion("mID not between", value1, value2, "mID");
            return (Criteria) this;
        }

        public Criteria andNmIsNull() {
            addCriterion("Nm is null");
            return (Criteria) this;
        }

        public Criteria andNmIsNotNull() {
            addCriterion("Nm is not null");
            return (Criteria) this;
        }

        public Criteria andNmEqualTo(String value) {
            addCriterion("Nm =", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotEqualTo(String value) {
            addCriterion("Nm <>", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmGreaterThan(String value) {
            addCriterion("Nm >", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmGreaterThanOrEqualTo(String value) {
            addCriterion("Nm >=", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmLessThan(String value) {
            addCriterion("Nm <", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmLessThanOrEqualTo(String value) {
            addCriterion("Nm <=", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmLike(String value) {
            addCriterion("Nm like", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotLike(String value) {
            addCriterion("Nm not like", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmIn(List<String> values) {
            addCriterion("Nm in", values, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotIn(List<String> values) {
            addCriterion("Nm not in", values, "nm");
            return (Criteria) this;
        }

        public Criteria andNmBetween(String value1, String value2) {
            addCriterion("Nm between", value1, value2, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotBetween(String value1, String value2) {
            addCriterion("Nm not between", value1, value2, "nm");
            return (Criteria) this;
        }

        public Criteria andDayNumberIsNull() {
            addCriterion("dayNumber is null");
            return (Criteria) this;
        }

        public Criteria andDayNumberIsNotNull() {
            addCriterion("dayNumber is not null");
            return (Criteria) this;
        }

        public Criteria andDayNumberEqualTo(Double value) {
            addCriterion("dayNumber =", value, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andDayNumberNotEqualTo(Double value) {
            addCriterion("dayNumber <>", value, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andDayNumberGreaterThan(Double value) {
            addCriterion("dayNumber >", value, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andDayNumberGreaterThanOrEqualTo(Double value) {
            addCriterion("dayNumber >=", value, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andDayNumberLessThan(Double value) {
            addCriterion("dayNumber <", value, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andDayNumberLessThanOrEqualTo(Double value) {
            addCriterion("dayNumber <=", value, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andDayNumberIn(List<Double> values) {
            addCriterion("dayNumber in", values, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andDayNumberNotIn(List<Double> values) {
            addCriterion("dayNumber not in", values, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andDayNumberBetween(Double value1, Double value2) {
            addCriterion("dayNumber between", value1, value2, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andDayNumberNotBetween(Double value1, Double value2) {
            addCriterion("dayNumber not between", value1, value2, "dayNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberIsNull() {
            addCriterion("theoryNumber is null");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberIsNotNull() {
            addCriterion("theoryNumber is not null");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberEqualTo(Double value) {
            addCriterion("theoryNumber =", value, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberNotEqualTo(Double value) {
            addCriterion("theoryNumber <>", value, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberGreaterThan(Double value) {
            addCriterion("theoryNumber >", value, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberGreaterThanOrEqualTo(Double value) {
            addCriterion("theoryNumber >=", value, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberLessThan(Double value) {
            addCriterion("theoryNumber <", value, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberLessThanOrEqualTo(Double value) {
            addCriterion("theoryNumber <=", value, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberIn(List<Double> values) {
            addCriterion("theoryNumber in", values, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberNotIn(List<Double> values) {
            addCriterion("theoryNumber not in", values, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberBetween(Double value1, Double value2) {
            addCriterion("theoryNumber between", value1, value2, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryNumberNotBetween(Double value1, Double value2) {
            addCriterion("theoryNumber not between", value1, value2, "theoryNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowIsNull() {
            addCriterion("theoryFlow is null");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowIsNotNull() {
            addCriterion("theoryFlow is not null");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowEqualTo(Double value) {
            addCriterion("theoryFlow =", value, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowNotEqualTo(Double value) {
            addCriterion("theoryFlow <>", value, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowGreaterThan(Double value) {
            addCriterion("theoryFlow >", value, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowGreaterThanOrEqualTo(Double value) {
            addCriterion("theoryFlow >=", value, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowLessThan(Double value) {
            addCriterion("theoryFlow <", value, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowLessThanOrEqualTo(Double value) {
            addCriterion("theoryFlow <=", value, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowIn(List<Double> values) {
            addCriterion("theoryFlow in", values, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowNotIn(List<Double> values) {
            addCriterion("theoryFlow not in", values, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowBetween(Double value1, Double value2) {
            addCriterion("theoryFlow between", value1, value2, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryFlowNotBetween(Double value1, Double value2) {
            addCriterion("theoryFlow not between", value1, value2, "theoryFlow");
            return (Criteria) this;
        }

        public Criteria andAreaIDIsNull() {
            addCriterion("areaID is null");
            return (Criteria) this;
        }

        public Criteria andAreaIDIsNotNull() {
            addCriterion("areaID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIDEqualTo(String value) {
            addCriterion("areaID =", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDNotEqualTo(String value) {
            addCriterion("areaID <>", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDGreaterThan(String value) {
            addCriterion("areaID >", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDGreaterThanOrEqualTo(String value) {
            addCriterion("areaID >=", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDLessThan(String value) {
            addCriterion("areaID <", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDLessThanOrEqualTo(String value) {
            addCriterion("areaID <=", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDLike(String value) {
            addCriterion("areaID like", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDNotLike(String value) {
            addCriterion("areaID not like", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDIn(List<String> values) {
            addCriterion("areaID in", values, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDNotIn(List<String> values) {
            addCriterion("areaID not in", values, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDBetween(String value1, String value2) {
            addCriterion("areaID between", value1, value2, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDNotBetween(String value1, String value2) {
            addCriterion("areaID not between", value1, value2, "areaID");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagIsNull() {
            addCriterion("theoryFlag is null");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagIsNotNull() {
            addCriterion("theoryFlag is not null");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagEqualTo(Integer value) {
            addCriterion("theoryFlag =", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagNotEqualTo(Integer value) {
            addCriterion("theoryFlag <>", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagGreaterThan(Integer value) {
            addCriterion("theoryFlag >", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("theoryFlag >=", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagLessThan(Integer value) {
            addCriterion("theoryFlag <", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagLessThanOrEqualTo(Integer value) {
            addCriterion("theoryFlag <=", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagIn(List<Integer> values) {
            addCriterion("theoryFlag in", values, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagNotIn(List<Integer> values) {
            addCriterion("theoryFlag not in", values, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagBetween(Integer value1, Integer value2) {
            addCriterion("theoryFlag between", value1, value2, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("theoryFlag not between", value1, value2, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagIsNull() {
            addCriterion("analyseFlag is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagIsNotNull() {
            addCriterion("analyseFlag is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagEqualTo(Integer value) {
            addCriterion("analyseFlag =", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagNotEqualTo(Integer value) {
            addCriterion("analyseFlag <>", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagGreaterThan(Integer value) {
            addCriterion("analyseFlag >", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("analyseFlag >=", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagLessThan(Integer value) {
            addCriterion("analyseFlag <", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagLessThanOrEqualTo(Integer value) {
            addCriterion("analyseFlag <=", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagIn(List<Integer> values) {
            addCriterion("analyseFlag in", values, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagNotIn(List<Integer> values) {
            addCriterion("analyseFlag not in", values, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagBetween(Integer value1, Integer value2) {
            addCriterion("analyseFlag between", value1, value2, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("analyseFlag not between", value1, value2, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("startTime is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("startTime is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(String value) {
            addCriterion("startTime =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("startTime <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(String value) {
            addCriterion("startTime >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("startTime >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(String value) {
            addCriterion("startTime <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("startTime <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLike(String value) {
            addCriterion("startTime like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotLike(String value) {
            addCriterion("startTime not like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<String> values) {
            addCriterion("startTime in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("startTime not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("startTime between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("startTime not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("endTime is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("endTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(String value) {
            addCriterion("endTime =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("endTime <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(String value) {
            addCriterion("endTime >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("endTime >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(String value) {
            addCriterion("endTime <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("endTime <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLike(String value) {
            addCriterion("endTime like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotLike(String value) {
            addCriterion("endTime not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<String> values) {
            addCriterion("endTime in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("endTime not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("endTime between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("endTime not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andWorkNumberIsNull() {
            addCriterion("workNumber is null");
            return (Criteria) this;
        }

        public Criteria andWorkNumberIsNotNull() {
            addCriterion("workNumber is not null");
            return (Criteria) this;
        }

        public Criteria andWorkNumberEqualTo(Double value) {
            addCriterion("workNumber =", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberNotEqualTo(Double value) {
            addCriterion("workNumber <>", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberGreaterThan(Double value) {
            addCriterion("workNumber >", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberGreaterThanOrEqualTo(Double value) {
            addCriterion("workNumber >=", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberLessThan(Double value) {
            addCriterion("workNumber <", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberLessThanOrEqualTo(Double value) {
            addCriterion("workNumber <=", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberIn(List<Double> values) {
            addCriterion("workNumber in", values, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberNotIn(List<Double> values) {
            addCriterion("workNumber not in", values, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberBetween(Double value1, Double value2) {
            addCriterion("workNumber between", value1, value2, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberNotBetween(Double value1, Double value2) {
            addCriterion("workNumber not between", value1, value2, "workNumber");
            return (Criteria) this;
        }

        public Criteria andDayFlowIsNull() {
            addCriterion("dayFlow is null");
            return (Criteria) this;
        }

        public Criteria andDayFlowIsNotNull() {
            addCriterion("dayFlow is not null");
            return (Criteria) this;
        }

        public Criteria andDayFlowEqualTo(Double value) {
            addCriterion("dayFlow =", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowNotEqualTo(Double value) {
            addCriterion("dayFlow <>", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowGreaterThan(Double value) {
            addCriterion("dayFlow >", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowGreaterThanOrEqualTo(Double value) {
            addCriterion("dayFlow >=", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowLessThan(Double value) {
            addCriterion("dayFlow <", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowLessThanOrEqualTo(Double value) {
            addCriterion("dayFlow <=", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowIn(List<Double> values) {
            addCriterion("dayFlow in", values, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowNotIn(List<Double> values) {
            addCriterion("dayFlow not in", values, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowBetween(Double value1, Double value2) {
            addCriterion("dayFlow between", value1, value2, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowNotBetween(Double value1, Double value2) {
            addCriterion("dayFlow not between", value1, value2, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andCurNumberIsNull() {
            addCriterion("curNumber is null");
            return (Criteria) this;
        }

        public Criteria andCurNumberIsNotNull() {
            addCriterion("curNumber is not null");
            return (Criteria) this;
        }

        public Criteria andCurNumberEqualTo(Double value) {
            addCriterion("curNumber =", value, "curNumber");
            return (Criteria) this;
        }

        public Criteria andCurNumberNotEqualTo(Double value) {
            addCriterion("curNumber <>", value, "curNumber");
            return (Criteria) this;
        }

        public Criteria andCurNumberGreaterThan(Double value) {
            addCriterion("curNumber >", value, "curNumber");
            return (Criteria) this;
        }

        public Criteria andCurNumberGreaterThanOrEqualTo(Double value) {
            addCriterion("curNumber >=", value, "curNumber");
            return (Criteria) this;
        }

        public Criteria andCurNumberLessThan(Double value) {
            addCriterion("curNumber <", value, "curNumber");
            return (Criteria) this;
        }

        public Criteria andCurNumberLessThanOrEqualTo(Double value) {
            addCriterion("curNumber <=", value, "curNumber");
            return (Criteria) this;
        }

        public Criteria andCurNumberIn(List<Double> values) {
            addCriterion("curNumber in", values, "curNumber");
            return (Criteria) this;
        }

        public Criteria andCurNumberNotIn(List<Double> values) {
            addCriterion("curNumber not in", values, "curNumber");
            return (Criteria) this;
        }

        public Criteria andCurNumberBetween(Double value1, Double value2) {
            addCriterion("curNumber between", value1, value2, "curNumber");
            return (Criteria) this;
        }

        public Criteria andCurNumberNotBetween(Double value1, Double value2) {
            addCriterion("curNumber not between", value1, value2, "curNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 11 20:36:43 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}