package com.flycode.dayaccount.entity;

public class TabDayAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.infoID
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Integer infoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.collectDay
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private String collectDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.mID
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Integer mID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.Nm
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.dayNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Double dayNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.theoryNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Double theoryNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.theoryFlow
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Double theoryFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.areaID
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private String areaID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.theoryFlag
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Integer theoryFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.analyseFlag
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Integer analyseFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.startTime
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.endTime
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.workNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Double workNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.dayFlow
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Double dayFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_dayAccount2015.curNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    private Double curNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.infoID
     *
     * @return the value of tab_dayAccount2015.infoID
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Integer getInfoID() {
        return infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.infoID
     *
     * @param infoID the value for tab_dayAccount2015.infoID
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setInfoID(Integer infoID) {
        this.infoID = infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.collectDay
     *
     * @return the value of tab_dayAccount2015.collectDay
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public String getCollectDay() {
        return collectDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.collectDay
     *
     * @param collectDay the value for tab_dayAccount2015.collectDay
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setCollectDay(String collectDay) {
        this.collectDay = collectDay == null ? null : collectDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.mID
     *
     * @return the value of tab_dayAccount2015.mID
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Integer getmID() {
        return mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.mID
     *
     * @param mID the value for tab_dayAccount2015.mID
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setmID(Integer mID) {
        this.mID = mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.Nm
     *
     * @return the value of tab_dayAccount2015.Nm
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.Nm
     *
     * @param nm the value for tab_dayAccount2015.Nm
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.dayNumber
     *
     * @return the value of tab_dayAccount2015.dayNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Double getDayNumber() {
        return dayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.dayNumber
     *
     * @param dayNumber the value for tab_dayAccount2015.dayNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setDayNumber(Double dayNumber) {
        this.dayNumber = dayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.theoryNumber
     *
     * @return the value of tab_dayAccount2015.theoryNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Double getTheoryNumber() {
        return theoryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.theoryNumber
     *
     * @param theoryNumber the value for tab_dayAccount2015.theoryNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setTheoryNumber(Double theoryNumber) {
        this.theoryNumber = theoryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.theoryFlow
     *
     * @return the value of tab_dayAccount2015.theoryFlow
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Double getTheoryFlow() {
        return theoryFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.theoryFlow
     *
     * @param theoryFlow the value for tab_dayAccount2015.theoryFlow
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setTheoryFlow(Double theoryFlow) {
        this.theoryFlow = theoryFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.areaID
     *
     * @return the value of tab_dayAccount2015.areaID
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public String getAreaID() {
        return areaID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.areaID
     *
     * @param areaID the value for tab_dayAccount2015.areaID
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setAreaID(String areaID) {
        this.areaID = areaID == null ? null : areaID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.theoryFlag
     *
     * @return the value of tab_dayAccount2015.theoryFlag
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Integer getTheoryFlag() {
        return theoryFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.theoryFlag
     *
     * @param theoryFlag the value for tab_dayAccount2015.theoryFlag
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setTheoryFlag(Integer theoryFlag) {
        this.theoryFlag = theoryFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.analyseFlag
     *
     * @return the value of tab_dayAccount2015.analyseFlag
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Integer getAnalyseFlag() {
        return analyseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.analyseFlag
     *
     * @param analyseFlag the value for tab_dayAccount2015.analyseFlag
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setAnalyseFlag(Integer analyseFlag) {
        this.analyseFlag = analyseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.startTime
     *
     * @return the value of tab_dayAccount2015.startTime
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.startTime
     *
     * @param startTime the value for tab_dayAccount2015.startTime
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.endTime
     *
     * @return the value of tab_dayAccount2015.endTime
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.endTime
     *
     * @param endTime the value for tab_dayAccount2015.endTime
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.workNumber
     *
     * @return the value of tab_dayAccount2015.workNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Double getWorkNumber() {
        return workNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.workNumber
     *
     * @param workNumber the value for tab_dayAccount2015.workNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setWorkNumber(Double workNumber) {
        this.workNumber = workNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.dayFlow
     *
     * @return the value of tab_dayAccount2015.dayFlow
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Double getDayFlow() {
        return dayFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.dayFlow
     *
     * @param dayFlow the value for tab_dayAccount2015.dayFlow
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setDayFlow(Double dayFlow) {
        this.dayFlow = dayFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_dayAccount2015.curNumber
     *
     * @return the value of tab_dayAccount2015.curNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public Double getCurNumber() {
        return curNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_dayAccount2015.curNumber
     *
     * @param curNumber the value for tab_dayAccount2015.curNumber
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    public void setCurNumber(Double curNumber) {
        this.curNumber = curNumber;
    }
}