package com.flycode.meter.entity;

public class TabMeter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.mID
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer mID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.adr
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String adr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.nm
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.cd
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String cd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.meterType
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String meterType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.mem
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String mem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.perNumber
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double perNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.curNumber
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double curNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.dosage
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.tFlow
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double tFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.readTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String readTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.mode
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.state
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.sID
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer sID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.infoID
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String infoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.ch
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer ch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.P
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double p;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.T
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.range_Hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double range_Hi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.range_Low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double range_Low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.dayDosage_hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double dayDosage_hi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.dayDosage_low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double dayDosage_low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.monDosage_hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double monDosage_hi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.monDosage_low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double monDosage_low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.stopFlag
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer stopFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.stopTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer stopTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.stopValue
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double stopValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.suspendTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String suspendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.unusual
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer unusual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.alarm1
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer alarm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.alarm2
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer alarm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.alarm3
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer alarm3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.alarm4
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer alarm4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.alarm5
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Integer alarm5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.minDayNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double minDayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.nowDay
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String nowDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.startDayTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String startDayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.minMonNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double minMonNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.nowMonth
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String nowMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.checkStopTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private String checkStopTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.dayNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double dayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.monthNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double monthNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.meterRange_Hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double meterRange_Hi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_meter.meterRange_Low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    private Double meterRange_Low;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.mID
     *
     * @return the value of tab_meter.mID
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getmID() {
        return mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.mID
     *
     * @param mID the value for tab_meter.mID
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setmID(Integer mID) {
        this.mID = mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.adr
     *
     * @return the value of tab_meter.adr
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getAdr() {
        return adr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.adr
     *
     * @param adr the value for tab_meter.adr
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setAdr(String adr) {
        this.adr = adr == null ? null : adr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.nm
     *
     * @return the value of tab_meter.nm
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.nm
     *
     * @param nm the value for tab_meter.nm
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.cd
     *
     * @return the value of tab_meter.cd
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.cd
     *
     * @param cd the value for tab_meter.cd
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setCd(String cd) {
        this.cd = cd == null ? null : cd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.meterType
     *
     * @return the value of tab_meter.meterType
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getMeterType() {
        return meterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.meterType
     *
     * @param meterType the value for tab_meter.meterType
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMeterType(String meterType) {
        this.meterType = meterType == null ? null : meterType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.mem
     *
     * @return the value of tab_meter.mem
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getMem() {
        return mem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.mem
     *
     * @param mem the value for tab_meter.mem
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMem(String mem) {
        this.mem = mem == null ? null : mem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.perNumber
     *
     * @return the value of tab_meter.perNumber
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getPerNumber() {
        return perNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.perNumber
     *
     * @param perNumber the value for tab_meter.perNumber
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setPerNumber(Double perNumber) {
        this.perNumber = perNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.curNumber
     *
     * @return the value of tab_meter.curNumber
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getCurNumber() {
        return curNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.curNumber
     *
     * @param curNumber the value for tab_meter.curNumber
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setCurNumber(Double curNumber) {
        this.curNumber = curNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.dosage
     *
     * @return the value of tab_meter.dosage
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.dosage
     *
     * @param dosage the value for tab_meter.dosage
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setDosage(Double dosage) {
        this.dosage = dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.tFlow
     *
     * @return the value of tab_meter.tFlow
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double gettFlow() {
        return tFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.tFlow
     *
     * @param tFlow the value for tab_meter.tFlow
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void settFlow(Double tFlow) {
        this.tFlow = tFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.readTime
     *
     * @return the value of tab_meter.readTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.readTime
     *
     * @param readTime the value for tab_meter.readTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setReadTime(String readTime) {
        this.readTime = readTime == null ? null : readTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.mode
     *
     * @return the value of tab_meter.mode
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.mode
     *
     * @param mode the value for tab_meter.mode
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.state
     *
     * @return the value of tab_meter.state
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.state
     *
     * @param state the value for tab_meter.state
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.sID
     *
     * @return the value of tab_meter.sID
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getsID() {
        return sID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.sID
     *
     * @param sID the value for tab_meter.sID
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setsID(Integer sID) {
        this.sID = sID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.infoID
     *
     * @return the value of tab_meter.infoID
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getInfoID() {
        return infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.infoID
     *
     * @param infoID the value for tab_meter.infoID
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setInfoID(String infoID) {
        this.infoID = infoID == null ? null : infoID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.ch
     *
     * @return the value of tab_meter.ch
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getCh() {
        return ch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.ch
     *
     * @param ch the value for tab_meter.ch
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setCh(Integer ch) {
        this.ch = ch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.P
     *
     * @return the value of tab_meter.P
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getP() {
        return p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.P
     *
     * @param p the value for tab_meter.P
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setP(Double p) {
        this.p = p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.T
     *
     * @return the value of tab_meter.T
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getT() {
        return t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.T
     *
     * @param t the value for tab_meter.T
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setT(Double t) {
        this.t = t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.range_Hi
     *
     * @return the value of tab_meter.range_Hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getRange_Hi() {
        return range_Hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.range_Hi
     *
     * @param range_Hi the value for tab_meter.range_Hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setRange_Hi(Double range_Hi) {
        this.range_Hi = range_Hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.range_Low
     *
     * @return the value of tab_meter.range_Low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getRange_Low() {
        return range_Low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.range_Low
     *
     * @param range_Low the value for tab_meter.range_Low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setRange_Low(Double range_Low) {
        this.range_Low = range_Low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.dayDosage_hi
     *
     * @return the value of tab_meter.dayDosage_hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getDayDosage_hi() {
        return dayDosage_hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.dayDosage_hi
     *
     * @param dayDosage_hi the value for tab_meter.dayDosage_hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setDayDosage_hi(Double dayDosage_hi) {
        this.dayDosage_hi = dayDosage_hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.dayDosage_low
     *
     * @return the value of tab_meter.dayDosage_low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getDayDosage_low() {
        return dayDosage_low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.dayDosage_low
     *
     * @param dayDosage_low the value for tab_meter.dayDosage_low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setDayDosage_low(Double dayDosage_low) {
        this.dayDosage_low = dayDosage_low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.monDosage_hi
     *
     * @return the value of tab_meter.monDosage_hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getMonDosage_hi() {
        return monDosage_hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.monDosage_hi
     *
     * @param monDosage_hi the value for tab_meter.monDosage_hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMonDosage_hi(Double monDosage_hi) {
        this.monDosage_hi = monDosage_hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.monDosage_low
     *
     * @return the value of tab_meter.monDosage_low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getMonDosage_low() {
        return monDosage_low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.monDosage_low
     *
     * @param monDosage_low the value for tab_meter.monDosage_low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMonDosage_low(Double monDosage_low) {
        this.monDosage_low = monDosage_low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.stopFlag
     *
     * @return the value of tab_meter.stopFlag
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getStopFlag() {
        return stopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.stopFlag
     *
     * @param stopFlag the value for tab_meter.stopFlag
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setStopFlag(Integer stopFlag) {
        this.stopFlag = stopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.stopTime
     *
     * @return the value of tab_meter.stopTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.stopTime
     *
     * @param stopTime the value for tab_meter.stopTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setStopTime(Integer stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.stopValue
     *
     * @return the value of tab_meter.stopValue
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getStopValue() {
        return stopValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.stopValue
     *
     * @param stopValue the value for tab_meter.stopValue
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setStopValue(Double stopValue) {
        this.stopValue = stopValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.suspendTime
     *
     * @return the value of tab_meter.suspendTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getSuspendTime() {
        return suspendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.suspendTime
     *
     * @param suspendTime the value for tab_meter.suspendTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setSuspendTime(String suspendTime) {
        this.suspendTime = suspendTime == null ? null : suspendTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.unusual
     *
     * @return the value of tab_meter.unusual
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getUnusual() {
        return unusual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.unusual
     *
     * @param unusual the value for tab_meter.unusual
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setUnusual(Integer unusual) {
        this.unusual = unusual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.alarm1
     *
     * @return the value of tab_meter.alarm1
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getAlarm1() {
        return alarm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.alarm1
     *
     * @param alarm1 the value for tab_meter.alarm1
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setAlarm1(Integer alarm1) {
        this.alarm1 = alarm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.alarm2
     *
     * @return the value of tab_meter.alarm2
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getAlarm2() {
        return alarm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.alarm2
     *
     * @param alarm2 the value for tab_meter.alarm2
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setAlarm2(Integer alarm2) {
        this.alarm2 = alarm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.alarm3
     *
     * @return the value of tab_meter.alarm3
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getAlarm3() {
        return alarm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.alarm3
     *
     * @param alarm3 the value for tab_meter.alarm3
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setAlarm3(Integer alarm3) {
        this.alarm3 = alarm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.alarm4
     *
     * @return the value of tab_meter.alarm4
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getAlarm4() {
        return alarm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.alarm4
     *
     * @param alarm4 the value for tab_meter.alarm4
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setAlarm4(Integer alarm4) {
        this.alarm4 = alarm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.alarm5
     *
     * @return the value of tab_meter.alarm5
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Integer getAlarm5() {
        return alarm5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.alarm5
     *
     * @param alarm5 the value for tab_meter.alarm5
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setAlarm5(Integer alarm5) {
        this.alarm5 = alarm5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.minDayNum
     *
     * @return the value of tab_meter.minDayNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getMinDayNum() {
        return minDayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.minDayNum
     *
     * @param minDayNum the value for tab_meter.minDayNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMinDayNum(Double minDayNum) {
        this.minDayNum = minDayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.nowDay
     *
     * @return the value of tab_meter.nowDay
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getNowDay() {
        return nowDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.nowDay
     *
     * @param nowDay the value for tab_meter.nowDay
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setNowDay(String nowDay) {
        this.nowDay = nowDay == null ? null : nowDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.startDayTime
     *
     * @return the value of tab_meter.startDayTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getStartDayTime() {
        return startDayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.startDayTime
     *
     * @param startDayTime the value for tab_meter.startDayTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setStartDayTime(String startDayTime) {
        this.startDayTime = startDayTime == null ? null : startDayTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.minMonNum
     *
     * @return the value of tab_meter.minMonNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getMinMonNum() {
        return minMonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.minMonNum
     *
     * @param minMonNum the value for tab_meter.minMonNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMinMonNum(Double minMonNum) {
        this.minMonNum = minMonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.nowMonth
     *
     * @return the value of tab_meter.nowMonth
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getNowMonth() {
        return nowMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.nowMonth
     *
     * @param nowMonth the value for tab_meter.nowMonth
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setNowMonth(String nowMonth) {
        this.nowMonth = nowMonth == null ? null : nowMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.checkStopTime
     *
     * @return the value of tab_meter.checkStopTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public String getCheckStopTime() {
        return checkStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.checkStopTime
     *
     * @param checkStopTime the value for tab_meter.checkStopTime
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setCheckStopTime(String checkStopTime) {
        this.checkStopTime = checkStopTime == null ? null : checkStopTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.dayNum
     *
     * @return the value of tab_meter.dayNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getDayNum() {
        return dayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.dayNum
     *
     * @param dayNum the value for tab_meter.dayNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setDayNum(Double dayNum) {
        this.dayNum = dayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.monthNum
     *
     * @return the value of tab_meter.monthNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getMonthNum() {
        return monthNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.monthNum
     *
     * @param monthNum the value for tab_meter.monthNum
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMonthNum(Double monthNum) {
        this.monthNum = monthNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.meterRange_Hi
     *
     * @return the value of tab_meter.meterRange_Hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getMeterRange_Hi() {
        return meterRange_Hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.meterRange_Hi
     *
     * @param meterRange_Hi the value for tab_meter.meterRange_Hi
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMeterRange_Hi(Double meterRange_Hi) {
        this.meterRange_Hi = meterRange_Hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_meter.meterRange_Low
     *
     * @return the value of tab_meter.meterRange_Low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public Double getMeterRange_Low() {
        return meterRange_Low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_meter.meterRange_Low
     *
     * @param meterRange_Low the value for tab_meter.meterRange_Low
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    public void setMeterRange_Low(Double meterRange_Low) {
        this.meterRange_Low = meterRange_Low;
    }
}