package com.flycode.readerr.mapper;

import com.flycode.readerr.entity.TabReadErr;
import com.flycode.readerr.entity.TabReadErrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabReadErrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    int countByExample(TabReadErrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    int deleteByExample(TabReadErrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    int deleteByPrimaryKey(Integer infoID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    int insert(TabReadErr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    int insertSelective(TabReadErr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    List<TabReadErr> selectByExample(TabReadErrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    TabReadErr selectByPrimaryKey(Integer infoID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") TabReadErr record, @Param("example") TabReadErrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    int updateByExample(@Param("record") TabReadErr record, @Param("example") TabReadErrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    int updateByPrimaryKeySelective(TabReadErr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_readErr
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    int updateByPrimaryKey(TabReadErr record);
}