package com.flycode.masterop.entity;

public class TabMasterOp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.opID
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private Integer opID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.opNm
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private String opNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.opPwd
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private String opPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.sysID
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private String sysID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.visible
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private String visible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.opMemo
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private String opMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.loginState
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private String loginState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.loginTime
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private String loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.loginSerial
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private String loginSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_op.clientIP
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    private String clientIP;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.opID
     *
     * @return the value of tab_master_op.opID
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public Integer getOpID() {
        return opID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.opID
     *
     * @param opID the value for tab_master_op.opID
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setOpID(Integer opID) {
        this.opID = opID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.opNm
     *
     * @return the value of tab_master_op.opNm
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getOpNm() {
        return opNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.opNm
     *
     * @param opNm the value for tab_master_op.opNm
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setOpNm(String opNm) {
        this.opNm = opNm == null ? null : opNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.opPwd
     *
     * @return the value of tab_master_op.opPwd
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getOpPwd() {
        return opPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.opPwd
     *
     * @param opPwd the value for tab_master_op.opPwd
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setOpPwd(String opPwd) {
        this.opPwd = opPwd == null ? null : opPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.sysID
     *
     * @return the value of tab_master_op.sysID
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getSysID() {
        return sysID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.sysID
     *
     * @param sysID the value for tab_master_op.sysID
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setSysID(String sysID) {
        this.sysID = sysID == null ? null : sysID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.visible
     *
     * @return the value of tab_master_op.visible
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.visible
     *
     * @param visible the value for tab_master_op.visible
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setVisible(String visible) {
        this.visible = visible == null ? null : visible.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.opMemo
     *
     * @return the value of tab_master_op.opMemo
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getOpMemo() {
        return opMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.opMemo
     *
     * @param opMemo the value for tab_master_op.opMemo
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setOpMemo(String opMemo) {
        this.opMemo = opMemo == null ? null : opMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.loginState
     *
     * @return the value of tab_master_op.loginState
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getLoginState() {
        return loginState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.loginState
     *
     * @param loginState the value for tab_master_op.loginState
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setLoginState(String loginState) {
        this.loginState = loginState == null ? null : loginState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.loginTime
     *
     * @return the value of tab_master_op.loginTime
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.loginTime
     *
     * @param loginTime the value for tab_master_op.loginTime
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime == null ? null : loginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.loginSerial
     *
     * @return the value of tab_master_op.loginSerial
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getLoginSerial() {
        return loginSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.loginSerial
     *
     * @param loginSerial the value for tab_master_op.loginSerial
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setLoginSerial(String loginSerial) {
        this.loginSerial = loginSerial == null ? null : loginSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_op.clientIP
     *
     * @return the value of tab_master_op.clientIP
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getClientIP() {
        return clientIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_op.clientIP
     *
     * @param clientIP the value for tab_master_op.clientIP
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setClientIP(String clientIP) {
        this.clientIP = clientIP == null ? null : clientIP.trim();
    }
}