package com.flycode.masterop.entity;

import java.util.ArrayList;
import java.util.List;

public class TabMasterOpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public TabMasterOpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOpIDIsNull() {
            addCriterion("opID is null");
            return (Criteria) this;
        }

        public Criteria andOpIDIsNotNull() {
            addCriterion("opID is not null");
            return (Criteria) this;
        }

        public Criteria andOpIDEqualTo(Integer value) {
            addCriterion("opID =", value, "opID");
            return (Criteria) this;
        }

        public Criteria andOpIDNotEqualTo(Integer value) {
            addCriterion("opID <>", value, "opID");
            return (Criteria) this;
        }

        public Criteria andOpIDGreaterThan(Integer value) {
            addCriterion("opID >", value, "opID");
            return (Criteria) this;
        }

        public Criteria andOpIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("opID >=", value, "opID");
            return (Criteria) this;
        }

        public Criteria andOpIDLessThan(Integer value) {
            addCriterion("opID <", value, "opID");
            return (Criteria) this;
        }

        public Criteria andOpIDLessThanOrEqualTo(Integer value) {
            addCriterion("opID <=", value, "opID");
            return (Criteria) this;
        }

        public Criteria andOpIDIn(List<Integer> values) {
            addCriterion("opID in", values, "opID");
            return (Criteria) this;
        }

        public Criteria andOpIDNotIn(List<Integer> values) {
            addCriterion("opID not in", values, "opID");
            return (Criteria) this;
        }

        public Criteria andOpIDBetween(Integer value1, Integer value2) {
            addCriterion("opID between", value1, value2, "opID");
            return (Criteria) this;
        }

        public Criteria andOpIDNotBetween(Integer value1, Integer value2) {
            addCriterion("opID not between", value1, value2, "opID");
            return (Criteria) this;
        }

        public Criteria andOpNmIsNull() {
            addCriterion("opNm is null");
            return (Criteria) this;
        }

        public Criteria andOpNmIsNotNull() {
            addCriterion("opNm is not null");
            return (Criteria) this;
        }

        public Criteria andOpNmEqualTo(String value) {
            addCriterion("opNm =", value, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmNotEqualTo(String value) {
            addCriterion("opNm <>", value, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmGreaterThan(String value) {
            addCriterion("opNm >", value, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmGreaterThanOrEqualTo(String value) {
            addCriterion("opNm >=", value, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmLessThan(String value) {
            addCriterion("opNm <", value, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmLessThanOrEqualTo(String value) {
            addCriterion("opNm <=", value, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmLike(String value) {
            addCriterion("opNm like", value, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmNotLike(String value) {
            addCriterion("opNm not like", value, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmIn(List<String> values) {
            addCriterion("opNm in", values, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmNotIn(List<String> values) {
            addCriterion("opNm not in", values, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmBetween(String value1, String value2) {
            addCriterion("opNm between", value1, value2, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpNmNotBetween(String value1, String value2) {
            addCriterion("opNm not between", value1, value2, "opNm");
            return (Criteria) this;
        }

        public Criteria andOpPwdIsNull() {
            addCriterion("opPwd is null");
            return (Criteria) this;
        }

        public Criteria andOpPwdIsNotNull() {
            addCriterion("opPwd is not null");
            return (Criteria) this;
        }

        public Criteria andOpPwdEqualTo(String value) {
            addCriterion("opPwd =", value, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdNotEqualTo(String value) {
            addCriterion("opPwd <>", value, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdGreaterThan(String value) {
            addCriterion("opPwd >", value, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdGreaterThanOrEqualTo(String value) {
            addCriterion("opPwd >=", value, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdLessThan(String value) {
            addCriterion("opPwd <", value, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdLessThanOrEqualTo(String value) {
            addCriterion("opPwd <=", value, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdLike(String value) {
            addCriterion("opPwd like", value, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdNotLike(String value) {
            addCriterion("opPwd not like", value, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdIn(List<String> values) {
            addCriterion("opPwd in", values, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdNotIn(List<String> values) {
            addCriterion("opPwd not in", values, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdBetween(String value1, String value2) {
            addCriterion("opPwd between", value1, value2, "opPwd");
            return (Criteria) this;
        }

        public Criteria andOpPwdNotBetween(String value1, String value2) {
            addCriterion("opPwd not between", value1, value2, "opPwd");
            return (Criteria) this;
        }

        public Criteria andSysIDIsNull() {
            addCriterion("`sysID` is null");
            return (Criteria) this;
        }

        public Criteria andSysIDIsNotNull() {
            addCriterion("`sysID` is not null");
            return (Criteria) this;
        }

        public Criteria andSysIDEqualTo(String value) {
            addCriterion("`sysID` =", value, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDNotEqualTo(String value) {
            addCriterion("`sysID` <>", value, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDGreaterThan(String value) {
            addCriterion("`sysID` >", value, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDGreaterThanOrEqualTo(String value) {
            addCriterion("`sysID` >=", value, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDLessThan(String value) {
            addCriterion("`sysID` <", value, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDLessThanOrEqualTo(String value) {
            addCriterion("`sysID` <=", value, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDLike(String value) {
            addCriterion("`sysID` like", value, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDNotLike(String value) {
            addCriterion("`sysID` not like", value, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDIn(List<String> values) {
            addCriterion("`sysID` in", values, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDNotIn(List<String> values) {
            addCriterion("`sysID` not in", values, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDBetween(String value1, String value2) {
            addCriterion("`sysID` between", value1, value2, "sysID");
            return (Criteria) this;
        }

        public Criteria andSysIDNotBetween(String value1, String value2) {
            addCriterion("`sysID` not between", value1, value2, "sysID");
            return (Criteria) this;
        }

        public Criteria andVisibleIsNull() {
            addCriterion("visible is null");
            return (Criteria) this;
        }

        public Criteria andVisibleIsNotNull() {
            addCriterion("visible is not null");
            return (Criteria) this;
        }

        public Criteria andVisibleEqualTo(String value) {
            addCriterion("visible =", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleNotEqualTo(String value) {
            addCriterion("visible <>", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleGreaterThan(String value) {
            addCriterion("visible >", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleGreaterThanOrEqualTo(String value) {
            addCriterion("visible >=", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleLessThan(String value) {
            addCriterion("visible <", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleLessThanOrEqualTo(String value) {
            addCriterion("visible <=", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleLike(String value) {
            addCriterion("visible like", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleNotLike(String value) {
            addCriterion("visible not like", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleIn(List<String> values) {
            addCriterion("visible in", values, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleNotIn(List<String> values) {
            addCriterion("visible not in", values, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleBetween(String value1, String value2) {
            addCriterion("visible between", value1, value2, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleNotBetween(String value1, String value2) {
            addCriterion("visible not between", value1, value2, "visible");
            return (Criteria) this;
        }

        public Criteria andOpMemoIsNull() {
            addCriterion("opMemo is null");
            return (Criteria) this;
        }

        public Criteria andOpMemoIsNotNull() {
            addCriterion("opMemo is not null");
            return (Criteria) this;
        }

        public Criteria andOpMemoEqualTo(String value) {
            addCriterion("opMemo =", value, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoNotEqualTo(String value) {
            addCriterion("opMemo <>", value, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoGreaterThan(String value) {
            addCriterion("opMemo >", value, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoGreaterThanOrEqualTo(String value) {
            addCriterion("opMemo >=", value, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoLessThan(String value) {
            addCriterion("opMemo <", value, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoLessThanOrEqualTo(String value) {
            addCriterion("opMemo <=", value, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoLike(String value) {
            addCriterion("opMemo like", value, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoNotLike(String value) {
            addCriterion("opMemo not like", value, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoIn(List<String> values) {
            addCriterion("opMemo in", values, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoNotIn(List<String> values) {
            addCriterion("opMemo not in", values, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoBetween(String value1, String value2) {
            addCriterion("opMemo between", value1, value2, "opMemo");
            return (Criteria) this;
        }

        public Criteria andOpMemoNotBetween(String value1, String value2) {
            addCriterion("opMemo not between", value1, value2, "opMemo");
            return (Criteria) this;
        }

        public Criteria andLoginStateIsNull() {
            addCriterion("loginState is null");
            return (Criteria) this;
        }

        public Criteria andLoginStateIsNotNull() {
            addCriterion("loginState is not null");
            return (Criteria) this;
        }

        public Criteria andLoginStateEqualTo(String value) {
            addCriterion("loginState =", value, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateNotEqualTo(String value) {
            addCriterion("loginState <>", value, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateGreaterThan(String value) {
            addCriterion("loginState >", value, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateGreaterThanOrEqualTo(String value) {
            addCriterion("loginState >=", value, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateLessThan(String value) {
            addCriterion("loginState <", value, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateLessThanOrEqualTo(String value) {
            addCriterion("loginState <=", value, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateLike(String value) {
            addCriterion("loginState like", value, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateNotLike(String value) {
            addCriterion("loginState not like", value, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateIn(List<String> values) {
            addCriterion("loginState in", values, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateNotIn(List<String> values) {
            addCriterion("loginState not in", values, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateBetween(String value1, String value2) {
            addCriterion("loginState between", value1, value2, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginStateNotBetween(String value1, String value2) {
            addCriterion("loginState not between", value1, value2, "loginState");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNull() {
            addCriterion("loginTime is null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNotNull() {
            addCriterion("loginTime is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeEqualTo(String value) {
            addCriterion("loginTime =", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotEqualTo(String value) {
            addCriterion("loginTime <>", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThan(String value) {
            addCriterion("loginTime >", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThanOrEqualTo(String value) {
            addCriterion("loginTime >=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThan(String value) {
            addCriterion("loginTime <", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThanOrEqualTo(String value) {
            addCriterion("loginTime <=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLike(String value) {
            addCriterion("loginTime like", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotLike(String value) {
            addCriterion("loginTime not like", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIn(List<String> values) {
            addCriterion("loginTime in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotIn(List<String> values) {
            addCriterion("loginTime not in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeBetween(String value1, String value2) {
            addCriterion("loginTime between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotBetween(String value1, String value2) {
            addCriterion("loginTime not between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginSerialIsNull() {
            addCriterion("loginSerial is null");
            return (Criteria) this;
        }

        public Criteria andLoginSerialIsNotNull() {
            addCriterion("loginSerial is not null");
            return (Criteria) this;
        }

        public Criteria andLoginSerialEqualTo(String value) {
            addCriterion("loginSerial =", value, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialNotEqualTo(String value) {
            addCriterion("loginSerial <>", value, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialGreaterThan(String value) {
            addCriterion("loginSerial >", value, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialGreaterThanOrEqualTo(String value) {
            addCriterion("loginSerial >=", value, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialLessThan(String value) {
            addCriterion("loginSerial <", value, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialLessThanOrEqualTo(String value) {
            addCriterion("loginSerial <=", value, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialLike(String value) {
            addCriterion("loginSerial like", value, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialNotLike(String value) {
            addCriterion("loginSerial not like", value, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialIn(List<String> values) {
            addCriterion("loginSerial in", values, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialNotIn(List<String> values) {
            addCriterion("loginSerial not in", values, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialBetween(String value1, String value2) {
            addCriterion("loginSerial between", value1, value2, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andLoginSerialNotBetween(String value1, String value2) {
            addCriterion("loginSerial not between", value1, value2, "loginSerial");
            return (Criteria) this;
        }

        public Criteria andClientIPIsNull() {
            addCriterion("clientIP is null");
            return (Criteria) this;
        }

        public Criteria andClientIPIsNotNull() {
            addCriterion("clientIP is not null");
            return (Criteria) this;
        }

        public Criteria andClientIPEqualTo(String value) {
            addCriterion("clientIP =", value, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPNotEqualTo(String value) {
            addCriterion("clientIP <>", value, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPGreaterThan(String value) {
            addCriterion("clientIP >", value, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPGreaterThanOrEqualTo(String value) {
            addCriterion("clientIP >=", value, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPLessThan(String value) {
            addCriterion("clientIP <", value, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPLessThanOrEqualTo(String value) {
            addCriterion("clientIP <=", value, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPLike(String value) {
            addCriterion("clientIP like", value, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPNotLike(String value) {
            addCriterion("clientIP not like", value, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPIn(List<String> values) {
            addCriterion("clientIP in", values, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPNotIn(List<String> values) {
            addCriterion("clientIP not in", values, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPBetween(String value1, String value2) {
            addCriterion("clientIP between", value1, value2, "clientIP");
            return (Criteria) this;
        }

        public Criteria andClientIPNotBetween(String value1, String value2) {
            addCriterion("clientIP not between", value1, value2, "clientIP");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_master_op
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 16 22:19:18 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_master_op
     *
     * @mbggenerated Mon Nov 16 22:19:18 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}