package com.flycode.oplience.entity;

public class TabMasterOpLience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_opLience.funID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    private Integer funID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_opLience.opID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    private Integer opID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_opLience.mID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    private Integer mID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_opLience.nm
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_master_opLience.infoID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    private String infoID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_opLience.funID
     *
     * @return the value of tab_master_opLience.funID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public Integer getFunID() {
        return funID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_opLience.funID
     *
     * @param funID the value for tab_master_opLience.funID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public void setFunID(Integer funID) {
        this.funID = funID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_opLience.opID
     *
     * @return the value of tab_master_opLience.opID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public Integer getOpID() {
        return opID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_opLience.opID
     *
     * @param opID the value for tab_master_opLience.opID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public void setOpID(Integer opID) {
        this.opID = opID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_opLience.mID
     *
     * @return the value of tab_master_opLience.mID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public Integer getmID() {
        return mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_opLience.mID
     *
     * @param mID the value for tab_master_opLience.mID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public void setmID(Integer mID) {
        this.mID = mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_opLience.nm
     *
     * @return the value of tab_master_opLience.nm
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_opLience.nm
     *
     * @param nm the value for tab_master_opLience.nm
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_master_opLience.infoID
     *
     * @return the value of tab_master_opLience.infoID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public String getInfoID() {
        return infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_master_opLience.infoID
     *
     * @param infoID the value for tab_master_opLience.infoID
     *
     * @mbggenerated Mon Nov 16 14:12:42 CST 2015
     */
    public void setInfoID(String infoID) {
        this.infoID = infoID == null ? null : infoID.trim();
    }
}