package com.flycode.dayaccount.mapper;

import com.flycode.dayaccount.entity.TabDayAccount;
import com.flycode.dayaccount.entity.TabDayAccountExample;
import java.util.List;

public interface TabDayAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    int insert(TabDayAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    int insertSelective(TabDayAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_dayAccount2015
     *
     * @mbggenerated Wed Nov 11 20:36:43 CST 2015
     */
    List<TabDayAccount> selectByExample(TabDayAccountExample example);
}