package com.flycode.meter.mapper;

import com.flycode.meter.entity.TabMeter;
import com.flycode.meter.entity.TabMeterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabMeterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    int countByExample(TabMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    int deleteByExample(TabMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    int deleteByPrimaryKey(Integer mID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    int insert(TabMeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    int insertSelective(TabMeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    List<TabMeter> selectByExample(TabMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    TabMeter selectByPrimaryKey(Integer mID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    int updateByExampleSelective(@Param("record") TabMeter record, @Param("example") TabMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    int updateByExample(@Param("record") TabMeter record, @Param("example") TabMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    int updateByPrimaryKeySelective(TabMeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_meter
     *
     * @mbggenerated Tue Nov 10 17:27:02 CST 2015
     */
    int updateByPrimaryKey(TabMeter record);
}