package com.flycode.area.entity;

public class TabArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_area.infoID
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    private String infoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_area.nm
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_area.level
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_area.mem
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    private String mem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_area.fatherID
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    private String fatherID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_area.infoID
     *
     * @return the value of tab_area.infoID
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public String getInfoID() {
        return infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_area.infoID
     *
     * @param infoID the value for tab_area.infoID
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public void setInfoID(String infoID) {
        this.infoID = infoID == null ? null : infoID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_area.nm
     *
     * @return the value of tab_area.nm
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_area.nm
     *
     * @param nm the value for tab_area.nm
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_area.level
     *
     * @return the value of tab_area.level
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_area.level
     *
     * @param level the value for tab_area.level
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_area.mem
     *
     * @return the value of tab_area.mem
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public String getMem() {
        return mem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_area.mem
     *
     * @param mem the value for tab_area.mem
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public void setMem(String mem) {
        this.mem = mem == null ? null : mem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_area.fatherID
     *
     * @return the value of tab_area.fatherID
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public String getFatherID() {
        return fatherID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_area.fatherID
     *
     * @param fatherID the value for tab_area.fatherID
     *
     * @mbggenerated Thu Nov 12 13:36:25 CST 2015
     */
    public void setFatherID(String fatherID) {
        this.fatherID = fatherID == null ? null : fatherID.trim();
    }
}