package com.flycode.log.entity;

public class TabLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_log.logID
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    private Integer logID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_log.id
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_log.logTime
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    private String logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_log.logInfo
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    private String logInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_log.sim
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    private String sim;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_log.logID
     *
     * @return the value of tab_log.logID
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public Integer getLogID() {
        return logID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_log.logID
     *
     * @param logID the value for tab_log.logID
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public void setLogID(Integer logID) {
        this.logID = logID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_log.id
     *
     * @return the value of tab_log.id
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_log.id
     *
     * @param id the value for tab_log.id
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_log.logTime
     *
     * @return the value of tab_log.logTime
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public String getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_log.logTime
     *
     * @param logTime the value for tab_log.logTime
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public void setLogTime(String logTime) {
        this.logTime = logTime == null ? null : logTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_log.logInfo
     *
     * @return the value of tab_log.logInfo
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public String getLogInfo() {
        return logInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_log.logInfo
     *
     * @param logInfo the value for tab_log.logInfo
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public void setLogInfo(String logInfo) {
        this.logInfo = logInfo == null ? null : logInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_log.sim
     *
     * @return the value of tab_log.sim
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public String getSim() {
        return sim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_log.sim
     *
     * @param sim the value for tab_log.sim
     *
     * @mbggenerated Fri Nov 13 11:14:55 CST 2015
     */
    public void setSim(String sim) {
        this.sim = sim == null ? null : sim.trim();
    }
}