package com.flycode.oplience.mapper;

import com.flycode.oplience.entity.TabMasterOpLience;
import com.flycode.oplience.entity.TabMasterOpLienceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabMasterOpLienceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	int countByExample(TabMasterOpLienceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	int deleteByExample(TabMasterOpLienceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	int deleteByPrimaryKey(Integer funID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	int insert(TabMasterOpLience record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	int insertSelective(TabMasterOpLience record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	List<TabMasterOpLience> selectByExample(TabMasterOpLienceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	TabMasterOpLience selectByPrimaryKey(Integer funID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TabMasterOpLience record,
			@Param("example") TabMasterOpLienceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	int updateByExample(@Param("record") TabMasterOpLience record,
			@Param("example") TabMasterOpLienceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	int updateByPrimaryKeySelective(TabMasterOpLience record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_master_opLience
	 * @mbggenerated  Tue Nov 17 17:01:50 CST 2015
	 */
	int updateByPrimaryKey(TabMasterOpLience record);
}