package com.flycode.readerr.entity;

public class TabReadErr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.infoID
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private Integer infoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.mID
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private Integer mID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.tFlow
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private Double tFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.curNumber
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private Double curNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.readTime
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private String readTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.Cd
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private String cd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.nm
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.comTime
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private String comTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.comFlag
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private String comFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.P
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private Double p;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.T
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private Double t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.errType
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private Integer errType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.opName
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private String opName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_readErr.processTime
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    private String processTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.infoID
     *
     * @return the value of tab_readErr.infoID
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public Integer getInfoID() {
        return infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.infoID
     *
     * @param infoID the value for tab_readErr.infoID
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setInfoID(Integer infoID) {
        this.infoID = infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.mID
     *
     * @return the value of tab_readErr.mID
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public Integer getmID() {
        return mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.mID
     *
     * @param mID the value for tab_readErr.mID
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setmID(Integer mID) {
        this.mID = mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.tFlow
     *
     * @return the value of tab_readErr.tFlow
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public Double gettFlow() {
        return tFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.tFlow
     *
     * @param tFlow the value for tab_readErr.tFlow
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void settFlow(Double tFlow) {
        this.tFlow = tFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.curNumber
     *
     * @return the value of tab_readErr.curNumber
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public Double getCurNumber() {
        return curNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.curNumber
     *
     * @param curNumber the value for tab_readErr.curNumber
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setCurNumber(Double curNumber) {
        this.curNumber = curNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.readTime
     *
     * @return the value of tab_readErr.readTime
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public String getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.readTime
     *
     * @param readTime the value for tab_readErr.readTime
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setReadTime(String readTime) {
        this.readTime = readTime == null ? null : readTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.Cd
     *
     * @return the value of tab_readErr.Cd
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public String getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.Cd
     *
     * @param cd the value for tab_readErr.Cd
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setCd(String cd) {
        this.cd = cd == null ? null : cd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.nm
     *
     * @return the value of tab_readErr.nm
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.nm
     *
     * @param nm the value for tab_readErr.nm
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.comTime
     *
     * @return the value of tab_readErr.comTime
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public String getComTime() {
        return comTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.comTime
     *
     * @param comTime the value for tab_readErr.comTime
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setComTime(String comTime) {
        this.comTime = comTime == null ? null : comTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.comFlag
     *
     * @return the value of tab_readErr.comFlag
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public String getComFlag() {
        return comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.comFlag
     *
     * @param comFlag the value for tab_readErr.comFlag
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setComFlag(String comFlag) {
        this.comFlag = comFlag == null ? null : comFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.P
     *
     * @return the value of tab_readErr.P
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public Double getP() {
        return p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.P
     *
     * @param p the value for tab_readErr.P
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setP(Double p) {
        this.p = p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.T
     *
     * @return the value of tab_readErr.T
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public Double getT() {
        return t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.T
     *
     * @param t the value for tab_readErr.T
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setT(Double t) {
        this.t = t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.errType
     *
     * @return the value of tab_readErr.errType
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public Integer getErrType() {
        return errType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.errType
     *
     * @param errType the value for tab_readErr.errType
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setErrType(Integer errType) {
        this.errType = errType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.opName
     *
     * @return the value of tab_readErr.opName
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public String getOpName() {
        return opName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.opName
     *
     * @param opName the value for tab_readErr.opName
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setOpName(String opName) {
        this.opName = opName == null ? null : opName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_readErr.processTime
     *
     * @return the value of tab_readErr.processTime
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public String getProcessTime() {
        return processTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_readErr.processTime
     *
     * @param processTime the value for tab_readErr.processTime
     *
     * @mbggenerated Thu Nov 12 20:47:40 CST 2015
     */
    public void setProcessTime(String processTime) {
        this.processTime = processTime == null ? null : processTime.trim();
    }
}