package com.flycode.error.entity;

import java.util.ArrayList;
import java.util.List;

public class TabErrorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public TabErrorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInfoIDIsNull() {
            addCriterion("infoID is null");
            return (Criteria) this;
        }

        public Criteria andInfoIDIsNotNull() {
            addCriterion("infoID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIDEqualTo(Integer value) {
            addCriterion("infoID =", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDNotEqualTo(Integer value) {
            addCriterion("infoID <>", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDGreaterThan(Integer value) {
            addCriterion("infoID >", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("infoID >=", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDLessThan(Integer value) {
            addCriterion("infoID <", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDLessThanOrEqualTo(Integer value) {
            addCriterion("infoID <=", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDIn(List<Integer> values) {
            addCriterion("infoID in", values, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDNotIn(List<Integer> values) {
            addCriterion("infoID not in", values, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDBetween(Integer value1, Integer value2) {
            addCriterion("infoID between", value1, value2, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDNotBetween(Integer value1, Integer value2) {
            addCriterion("infoID not between", value1, value2, "infoID");
            return (Criteria) this;
        }

        public Criteria andMIDIsNull() {
            addCriterion("mID is null");
            return (Criteria) this;
        }

        public Criteria andMIDIsNotNull() {
            addCriterion("mID is not null");
            return (Criteria) this;
        }

        public Criteria andMIDEqualTo(Integer value) {
            addCriterion("mID =", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDNotEqualTo(Integer value) {
            addCriterion("mID <>", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDGreaterThan(Integer value) {
            addCriterion("mID >", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("mID >=", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDLessThan(Integer value) {
            addCriterion("mID <", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDLessThanOrEqualTo(Integer value) {
            addCriterion("mID <=", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDIn(List<Integer> values) {
            addCriterion("mID in", values, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDNotIn(List<Integer> values) {
            addCriterion("mID not in", values, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDBetween(Integer value1, Integer value2) {
            addCriterion("mID between", value1, value2, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDNotBetween(Integer value1, Integer value2) {
            addCriterion("mID not between", value1, value2, "mID");
            return (Criteria) this;
        }

        public Criteria andNmIsNull() {
            addCriterion("nm is null");
            return (Criteria) this;
        }

        public Criteria andNmIsNotNull() {
            addCriterion("nm is not null");
            return (Criteria) this;
        }

        public Criteria andNmEqualTo(String value) {
            addCriterion("nm =", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotEqualTo(String value) {
            addCriterion("nm <>", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmGreaterThan(String value) {
            addCriterion("nm >", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmGreaterThanOrEqualTo(String value) {
            addCriterion("nm >=", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmLessThan(String value) {
            addCriterion("nm <", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmLessThanOrEqualTo(String value) {
            addCriterion("nm <=", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmLike(String value) {
            addCriterion("nm like", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotLike(String value) {
            addCriterion("nm not like", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmIn(List<String> values) {
            addCriterion("nm in", values, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotIn(List<String> values) {
            addCriterion("nm not in", values, "nm");
            return (Criteria) this;
        }

        public Criteria andNmBetween(String value1, String value2) {
            addCriterion("nm between", value1, value2, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotBetween(String value1, String value2) {
            addCriterion("nm not between", value1, value2, "nm");
            return (Criteria) this;
        }

        public Criteria andInfoIsNull() {
            addCriterion("info is null");
            return (Criteria) this;
        }

        public Criteria andInfoIsNotNull() {
            addCriterion("info is not null");
            return (Criteria) this;
        }

        public Criteria andInfoEqualTo(String value) {
            addCriterion("info =", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotEqualTo(String value) {
            addCriterion("info <>", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThan(String value) {
            addCriterion("info >", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThanOrEqualTo(String value) {
            addCriterion("info >=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThan(String value) {
            addCriterion("info <", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThanOrEqualTo(String value) {
            addCriterion("info <=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLike(String value) {
            addCriterion("info like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotLike(String value) {
            addCriterion("info not like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoIn(List<String> values) {
            addCriterion("info in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotIn(List<String> values) {
            addCriterion("info not in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoBetween(String value1, String value2) {
            addCriterion("info between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotBetween(String value1, String value2) {
            addCriterion("info not between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andReadTimeIsNull() {
            addCriterion("readTime is null");
            return (Criteria) this;
        }

        public Criteria andReadTimeIsNotNull() {
            addCriterion("readTime is not null");
            return (Criteria) this;
        }

        public Criteria andReadTimeEqualTo(String value) {
            addCriterion("readTime =", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeNotEqualTo(String value) {
            addCriterion("readTime <>", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeGreaterThan(String value) {
            addCriterion("readTime >", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeGreaterThanOrEqualTo(String value) {
            addCriterion("readTime >=", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeLessThan(String value) {
            addCriterion("readTime <", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeLessThanOrEqualTo(String value) {
            addCriterion("readTime <=", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeLike(String value) {
            addCriterion("readTime like", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeNotLike(String value) {
            addCriterion("readTime not like", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeIn(List<String> values) {
            addCriterion("readTime in", values, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeNotIn(List<String> values) {
            addCriterion("readTime not in", values, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeBetween(String value1, String value2) {
            addCriterion("readTime between", value1, value2, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeNotBetween(String value1, String value2) {
            addCriterion("readTime not between", value1, value2, "readTime");
            return (Criteria) this;
        }

        public Criteria andErrClassIsNull() {
            addCriterion("errClass is null");
            return (Criteria) this;
        }

        public Criteria andErrClassIsNotNull() {
            addCriterion("errClass is not null");
            return (Criteria) this;
        }

        public Criteria andErrClassEqualTo(String value) {
            addCriterion("errClass =", value, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassNotEqualTo(String value) {
            addCriterion("errClass <>", value, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassGreaterThan(String value) {
            addCriterion("errClass >", value, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassGreaterThanOrEqualTo(String value) {
            addCriterion("errClass >=", value, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassLessThan(String value) {
            addCriterion("errClass <", value, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassLessThanOrEqualTo(String value) {
            addCriterion("errClass <=", value, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassLike(String value) {
            addCriterion("errClass like", value, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassNotLike(String value) {
            addCriterion("errClass not like", value, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassIn(List<String> values) {
            addCriterion("errClass in", values, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassNotIn(List<String> values) {
            addCriterion("errClass not in", values, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassBetween(String value1, String value2) {
            addCriterion("errClass between", value1, value2, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrClassNotBetween(String value1, String value2) {
            addCriterion("errClass not between", value1, value2, "errClass");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagIsNull() {
            addCriterion("errProcessFlag is null");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagIsNotNull() {
            addCriterion("errProcessFlag is not null");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagEqualTo(Integer value) {
            addCriterion("errProcessFlag =", value, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagNotEqualTo(Integer value) {
            addCriterion("errProcessFlag <>", value, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagGreaterThan(Integer value) {
            addCriterion("errProcessFlag >", value, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("errProcessFlag >=", value, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagLessThan(Integer value) {
            addCriterion("errProcessFlag <", value, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagLessThanOrEqualTo(Integer value) {
            addCriterion("errProcessFlag <=", value, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagIn(List<Integer> values) {
            addCriterion("errProcessFlag in", values, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagNotIn(List<Integer> values) {
            addCriterion("errProcessFlag not in", values, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagBetween(Integer value1, Integer value2) {
            addCriterion("errProcessFlag between", value1, value2, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andErrProcessFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("errProcessFlag not between", value1, value2, "errProcessFlag");
            return (Criteria) this;
        }

        public Criteria andOPNmIsNull() {
            addCriterion("OPNm is null");
            return (Criteria) this;
        }

        public Criteria andOPNmIsNotNull() {
            addCriterion("OPNm is not null");
            return (Criteria) this;
        }

        public Criteria andOPNmEqualTo(String value) {
            addCriterion("OPNm =", value, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmNotEqualTo(String value) {
            addCriterion("OPNm <>", value, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmGreaterThan(String value) {
            addCriterion("OPNm >", value, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmGreaterThanOrEqualTo(String value) {
            addCriterion("OPNm >=", value, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmLessThan(String value) {
            addCriterion("OPNm <", value, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmLessThanOrEqualTo(String value) {
            addCriterion("OPNm <=", value, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmLike(String value) {
            addCriterion("OPNm like", value, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmNotLike(String value) {
            addCriterion("OPNm not like", value, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmIn(List<String> values) {
            addCriterion("OPNm in", values, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmNotIn(List<String> values) {
            addCriterion("OPNm not in", values, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmBetween(String value1, String value2) {
            addCriterion("OPNm between", value1, value2, "OPNm");
            return (Criteria) this;
        }

        public Criteria andOPNmNotBetween(String value1, String value2) {
            addCriterion("OPNm not between", value1, value2, "OPNm");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeIsNull() {
            addCriterion("errProcessTime is null");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeIsNotNull() {
            addCriterion("errProcessTime is not null");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeEqualTo(String value) {
            addCriterion("errProcessTime =", value, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeNotEqualTo(String value) {
            addCriterion("errProcessTime <>", value, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeGreaterThan(String value) {
            addCriterion("errProcessTime >", value, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeGreaterThanOrEqualTo(String value) {
            addCriterion("errProcessTime >=", value, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeLessThan(String value) {
            addCriterion("errProcessTime <", value, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeLessThanOrEqualTo(String value) {
            addCriterion("errProcessTime <=", value, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeLike(String value) {
            addCriterion("errProcessTime like", value, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeNotLike(String value) {
            addCriterion("errProcessTime not like", value, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeIn(List<String> values) {
            addCriterion("errProcessTime in", values, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeNotIn(List<String> values) {
            addCriterion("errProcessTime not in", values, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeBetween(String value1, String value2) {
            addCriterion("errProcessTime between", value1, value2, "errProcessTime");
            return (Criteria) this;
        }

        public Criteria andErrProcessTimeNotBetween(String value1, String value2) {
            addCriterion("errProcessTime not between", value1, value2, "errProcessTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_error
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 12 15:18:13 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_error
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}