package com.flycode.error.entity;

public class TabError {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_error.infoID
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    private Integer infoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_error.mID
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    private Integer mID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_error.nm
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_error.info
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_error.readTime
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    private String readTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_error.errClass
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    private String errClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_error.errProcessFlag
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    private Integer errProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_error.OPNm
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    private String OPNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_error.errProcessTime
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    private String errProcessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_error.infoID
     *
     * @return the value of tab_error.infoID
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public Integer getInfoID() {
        return infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_error.infoID
     *
     * @param infoID the value for tab_error.infoID
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setInfoID(Integer infoID) {
        this.infoID = infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_error.mID
     *
     * @return the value of tab_error.mID
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public Integer getmID() {
        return mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_error.mID
     *
     * @param mID the value for tab_error.mID
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setmID(Integer mID) {
        this.mID = mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_error.nm
     *
     * @return the value of tab_error.nm
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_error.nm
     *
     * @param nm the value for tab_error.nm
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_error.info
     *
     * @return the value of tab_error.info
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_error.info
     *
     * @param info the value for tab_error.info
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_error.readTime
     *
     * @return the value of tab_error.readTime
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public String getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_error.readTime
     *
     * @param readTime the value for tab_error.readTime
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setReadTime(String readTime) {
        this.readTime = readTime == null ? null : readTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_error.errClass
     *
     * @return the value of tab_error.errClass
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public String getErrClass() {
        return errClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_error.errClass
     *
     * @param errClass the value for tab_error.errClass
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setErrClass(String errClass) {
        this.errClass = errClass == null ? null : errClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_error.errProcessFlag
     *
     * @return the value of tab_error.errProcessFlag
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public Integer getErrProcessFlag() {
        return errProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_error.errProcessFlag
     *
     * @param errProcessFlag the value for tab_error.errProcessFlag
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setErrProcessFlag(Integer errProcessFlag) {
        this.errProcessFlag = errProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_error.OPNm
     *
     * @return the value of tab_error.OPNm
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public String getOPNm() {
        return OPNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_error.OPNm
     *
     * @param OPNm the value for tab_error.OPNm
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setOPNm(String OPNm) {
        this.OPNm = OPNm == null ? null : OPNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_error.errProcessTime
     *
     * @return the value of tab_error.errProcessTime
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public String getErrProcessTime() {
        return errProcessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_error.errProcessTime
     *
     * @param errProcessTime the value for tab_error.errProcessTime
     *
     * @mbggenerated Thu Nov 12 15:18:13 CST 2015
     */
    public void setErrProcessTime(String errProcessTime) {
        this.errProcessTime = errProcessTime == null ? null : errProcessTime.trim();
    }
}