package com.flycode.monthaccount.entity;

public class TabMonthAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.infoID
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private Integer infoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.collectMon
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private String collectMon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.mID
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private Integer mID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.Nm
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.monthNumber
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private Double monthNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.theoryMonNumber
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private Double theoryMonNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.theoryMonFlow
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private Double theoryMonFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.areaID
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private String areaID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.theoryFlag
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private Integer theoryFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.analyseFlag
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private Integer analyseFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.startTime
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_monthAccount.endTime
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    private String endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.infoID
     *
     * @return the value of tab_monthAccount.infoID
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public Integer getInfoID() {
        return infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.infoID
     *
     * @param infoID the value for tab_monthAccount.infoID
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setInfoID(Integer infoID) {
        this.infoID = infoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.collectMon
     *
     * @return the value of tab_monthAccount.collectMon
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public String getCollectMon() {
        return collectMon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.collectMon
     *
     * @param collectMon the value for tab_monthAccount.collectMon
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setCollectMon(String collectMon) {
        this.collectMon = collectMon == null ? null : collectMon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.mID
     *
     * @return the value of tab_monthAccount.mID
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public Integer getmID() {
        return mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.mID
     *
     * @param mID the value for tab_monthAccount.mID
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setmID(Integer mID) {
        this.mID = mID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.Nm
     *
     * @return the value of tab_monthAccount.Nm
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.Nm
     *
     * @param nm the value for tab_monthAccount.Nm
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.monthNumber
     *
     * @return the value of tab_monthAccount.monthNumber
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public Double getMonthNumber() {
        return monthNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.monthNumber
     *
     * @param monthNumber the value for tab_monthAccount.monthNumber
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setMonthNumber(Double monthNumber) {
        this.monthNumber = monthNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.theoryMonNumber
     *
     * @return the value of tab_monthAccount.theoryMonNumber
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public Double getTheoryMonNumber() {
        return theoryMonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.theoryMonNumber
     *
     * @param theoryMonNumber the value for tab_monthAccount.theoryMonNumber
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setTheoryMonNumber(Double theoryMonNumber) {
        this.theoryMonNumber = theoryMonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.theoryMonFlow
     *
     * @return the value of tab_monthAccount.theoryMonFlow
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public Double getTheoryMonFlow() {
        return theoryMonFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.theoryMonFlow
     *
     * @param theoryMonFlow the value for tab_monthAccount.theoryMonFlow
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setTheoryMonFlow(Double theoryMonFlow) {
        this.theoryMonFlow = theoryMonFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.areaID
     *
     * @return the value of tab_monthAccount.areaID
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public String getAreaID() {
        return areaID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.areaID
     *
     * @param areaID the value for tab_monthAccount.areaID
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setAreaID(String areaID) {
        this.areaID = areaID == null ? null : areaID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.theoryFlag
     *
     * @return the value of tab_monthAccount.theoryFlag
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public Integer getTheoryFlag() {
        return theoryFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.theoryFlag
     *
     * @param theoryFlag the value for tab_monthAccount.theoryFlag
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setTheoryFlag(Integer theoryFlag) {
        this.theoryFlag = theoryFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.analyseFlag
     *
     * @return the value of tab_monthAccount.analyseFlag
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public Integer getAnalyseFlag() {
        return analyseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.analyseFlag
     *
     * @param analyseFlag the value for tab_monthAccount.analyseFlag
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setAnalyseFlag(Integer analyseFlag) {
        this.analyseFlag = analyseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.startTime
     *
     * @return the value of tab_monthAccount.startTime
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.startTime
     *
     * @param startTime the value for tab_monthAccount.startTime
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_monthAccount.endTime
     *
     * @return the value of tab_monthAccount.endTime
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_monthAccount.endTime
     *
     * @param endTime the value for tab_monthAccount.endTime
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }
}