package com.flycode.monthaccount.entity;

import java.util.ArrayList;
import java.util.List;

public class TabMonthAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public TabMonthAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInfoIDIsNull() {
            addCriterion("infoID is null");
            return (Criteria) this;
        }

        public Criteria andInfoIDIsNotNull() {
            addCriterion("infoID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIDEqualTo(Integer value) {
            addCriterion("infoID =", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDNotEqualTo(Integer value) {
            addCriterion("infoID <>", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDGreaterThan(Integer value) {
            addCriterion("infoID >", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("infoID >=", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDLessThan(Integer value) {
            addCriterion("infoID <", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDLessThanOrEqualTo(Integer value) {
            addCriterion("infoID <=", value, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDIn(List<Integer> values) {
            addCriterion("infoID in", values, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDNotIn(List<Integer> values) {
            addCriterion("infoID not in", values, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDBetween(Integer value1, Integer value2) {
            addCriterion("infoID between", value1, value2, "infoID");
            return (Criteria) this;
        }

        public Criteria andInfoIDNotBetween(Integer value1, Integer value2) {
            addCriterion("infoID not between", value1, value2, "infoID");
            return (Criteria) this;
        }

        public Criteria andCollectMonIsNull() {
            addCriterion("collectMon is null");
            return (Criteria) this;
        }

        public Criteria andCollectMonIsNotNull() {
            addCriterion("collectMon is not null");
            return (Criteria) this;
        }

        public Criteria andCollectMonEqualTo(String value) {
            addCriterion("collectMon =", value, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonNotEqualTo(String value) {
            addCriterion("collectMon <>", value, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonGreaterThan(String value) {
            addCriterion("collectMon >", value, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonGreaterThanOrEqualTo(String value) {
            addCriterion("collectMon >=", value, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonLessThan(String value) {
            addCriterion("collectMon <", value, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonLessThanOrEqualTo(String value) {
            addCriterion("collectMon <=", value, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonLike(String value) {
            addCriterion("collectMon like", value, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonNotLike(String value) {
            addCriterion("collectMon not like", value, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonIn(List<String> values) {
            addCriterion("collectMon in", values, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonNotIn(List<String> values) {
            addCriterion("collectMon not in", values, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonBetween(String value1, String value2) {
            addCriterion("collectMon between", value1, value2, "collectMon");
            return (Criteria) this;
        }

        public Criteria andCollectMonNotBetween(String value1, String value2) {
            addCriterion("collectMon not between", value1, value2, "collectMon");
            return (Criteria) this;
        }

        public Criteria andMIDIsNull() {
            addCriterion("mID is null");
            return (Criteria) this;
        }

        public Criteria andMIDIsNotNull() {
            addCriterion("mID is not null");
            return (Criteria) this;
        }

        public Criteria andMIDEqualTo(Integer value) {
            addCriterion("mID =", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDNotEqualTo(Integer value) {
            addCriterion("mID <>", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDGreaterThan(Integer value) {
            addCriterion("mID >", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("mID >=", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDLessThan(Integer value) {
            addCriterion("mID <", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDLessThanOrEqualTo(Integer value) {
            addCriterion("mID <=", value, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDIn(List<Integer> values) {
            addCriterion("mID in", values, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDNotIn(List<Integer> values) {
            addCriterion("mID not in", values, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDBetween(Integer value1, Integer value2) {
            addCriterion("mID between", value1, value2, "mID");
            return (Criteria) this;
        }

        public Criteria andMIDNotBetween(Integer value1, Integer value2) {
            addCriterion("mID not between", value1, value2, "mID");
            return (Criteria) this;
        }

        public Criteria andNmIsNull() {
            addCriterion("Nm is null");
            return (Criteria) this;
        }

        public Criteria andNmIsNotNull() {
            addCriterion("Nm is not null");
            return (Criteria) this;
        }

        public Criteria andNmEqualTo(String value) {
            addCriterion("Nm =", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotEqualTo(String value) {
            addCriterion("Nm <>", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmGreaterThan(String value) {
            addCriterion("Nm >", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmGreaterThanOrEqualTo(String value) {
            addCriterion("Nm >=", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmLessThan(String value) {
            addCriterion("Nm <", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmLessThanOrEqualTo(String value) {
            addCriterion("Nm <=", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmLike(String value) {
            addCriterion("Nm like", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotLike(String value) {
            addCriterion("Nm not like", value, "nm");
            return (Criteria) this;
        }

        public Criteria andNmIn(List<String> values) {
            addCriterion("Nm in", values, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotIn(List<String> values) {
            addCriterion("Nm not in", values, "nm");
            return (Criteria) this;
        }

        public Criteria andNmBetween(String value1, String value2) {
            addCriterion("Nm between", value1, value2, "nm");
            return (Criteria) this;
        }

        public Criteria andNmNotBetween(String value1, String value2) {
            addCriterion("Nm not between", value1, value2, "nm");
            return (Criteria) this;
        }

        public Criteria andMonthNumberIsNull() {
            addCriterion("monthNumber is null");
            return (Criteria) this;
        }

        public Criteria andMonthNumberIsNotNull() {
            addCriterion("monthNumber is not null");
            return (Criteria) this;
        }

        public Criteria andMonthNumberEqualTo(Double value) {
            addCriterion("monthNumber =", value, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andMonthNumberNotEqualTo(Double value) {
            addCriterion("monthNumber <>", value, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andMonthNumberGreaterThan(Double value) {
            addCriterion("monthNumber >", value, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andMonthNumberGreaterThanOrEqualTo(Double value) {
            addCriterion("monthNumber >=", value, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andMonthNumberLessThan(Double value) {
            addCriterion("monthNumber <", value, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andMonthNumberLessThanOrEqualTo(Double value) {
            addCriterion("monthNumber <=", value, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andMonthNumberIn(List<Double> values) {
            addCriterion("monthNumber in", values, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andMonthNumberNotIn(List<Double> values) {
            addCriterion("monthNumber not in", values, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andMonthNumberBetween(Double value1, Double value2) {
            addCriterion("monthNumber between", value1, value2, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andMonthNumberNotBetween(Double value1, Double value2) {
            addCriterion("monthNumber not between", value1, value2, "monthNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberIsNull() {
            addCriterion("theoryMonNumber is null");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberIsNotNull() {
            addCriterion("theoryMonNumber is not null");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberEqualTo(Double value) {
            addCriterion("theoryMonNumber =", value, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberNotEqualTo(Double value) {
            addCriterion("theoryMonNumber <>", value, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberGreaterThan(Double value) {
            addCriterion("theoryMonNumber >", value, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberGreaterThanOrEqualTo(Double value) {
            addCriterion("theoryMonNumber >=", value, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberLessThan(Double value) {
            addCriterion("theoryMonNumber <", value, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberLessThanOrEqualTo(Double value) {
            addCriterion("theoryMonNumber <=", value, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberIn(List<Double> values) {
            addCriterion("theoryMonNumber in", values, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberNotIn(List<Double> values) {
            addCriterion("theoryMonNumber not in", values, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberBetween(Double value1, Double value2) {
            addCriterion("theoryMonNumber between", value1, value2, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonNumberNotBetween(Double value1, Double value2) {
            addCriterion("theoryMonNumber not between", value1, value2, "theoryMonNumber");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowIsNull() {
            addCriterion("theoryMonFlow is null");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowIsNotNull() {
            addCriterion("theoryMonFlow is not null");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowEqualTo(Double value) {
            addCriterion("theoryMonFlow =", value, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowNotEqualTo(Double value) {
            addCriterion("theoryMonFlow <>", value, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowGreaterThan(Double value) {
            addCriterion("theoryMonFlow >", value, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowGreaterThanOrEqualTo(Double value) {
            addCriterion("theoryMonFlow >=", value, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowLessThan(Double value) {
            addCriterion("theoryMonFlow <", value, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowLessThanOrEqualTo(Double value) {
            addCriterion("theoryMonFlow <=", value, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowIn(List<Double> values) {
            addCriterion("theoryMonFlow in", values, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowNotIn(List<Double> values) {
            addCriterion("theoryMonFlow not in", values, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowBetween(Double value1, Double value2) {
            addCriterion("theoryMonFlow between", value1, value2, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andTheoryMonFlowNotBetween(Double value1, Double value2) {
            addCriterion("theoryMonFlow not between", value1, value2, "theoryMonFlow");
            return (Criteria) this;
        }

        public Criteria andAreaIDIsNull() {
            addCriterion("areaID is null");
            return (Criteria) this;
        }

        public Criteria andAreaIDIsNotNull() {
            addCriterion("areaID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIDEqualTo(String value) {
            addCriterion("areaID =", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDNotEqualTo(String value) {
            addCriterion("areaID <>", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDGreaterThan(String value) {
            addCriterion("areaID >", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDGreaterThanOrEqualTo(String value) {
            addCriterion("areaID >=", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDLessThan(String value) {
            addCriterion("areaID <", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDLessThanOrEqualTo(String value) {
            addCriterion("areaID <=", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDLike(String value) {
            addCriterion("areaID like", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDNotLike(String value) {
            addCriterion("areaID not like", value, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDIn(List<String> values) {
            addCriterion("areaID in", values, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDNotIn(List<String> values) {
            addCriterion("areaID not in", values, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDBetween(String value1, String value2) {
            addCriterion("areaID between", value1, value2, "areaID");
            return (Criteria) this;
        }

        public Criteria andAreaIDNotBetween(String value1, String value2) {
            addCriterion("areaID not between", value1, value2, "areaID");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagIsNull() {
            addCriterion("theoryFlag is null");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagIsNotNull() {
            addCriterion("theoryFlag is not null");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagEqualTo(Integer value) {
            addCriterion("theoryFlag =", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagNotEqualTo(Integer value) {
            addCriterion("theoryFlag <>", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagGreaterThan(Integer value) {
            addCriterion("theoryFlag >", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("theoryFlag >=", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagLessThan(Integer value) {
            addCriterion("theoryFlag <", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagLessThanOrEqualTo(Integer value) {
            addCriterion("theoryFlag <=", value, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagIn(List<Integer> values) {
            addCriterion("theoryFlag in", values, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagNotIn(List<Integer> values) {
            addCriterion("theoryFlag not in", values, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagBetween(Integer value1, Integer value2) {
            addCriterion("theoryFlag between", value1, value2, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andTheoryFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("theoryFlag not between", value1, value2, "theoryFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagIsNull() {
            addCriterion("analyseFlag is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagIsNotNull() {
            addCriterion("analyseFlag is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagEqualTo(Integer value) {
            addCriterion("analyseFlag =", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagNotEqualTo(Integer value) {
            addCriterion("analyseFlag <>", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagGreaterThan(Integer value) {
            addCriterion("analyseFlag >", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("analyseFlag >=", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagLessThan(Integer value) {
            addCriterion("analyseFlag <", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagLessThanOrEqualTo(Integer value) {
            addCriterion("analyseFlag <=", value, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagIn(List<Integer> values) {
            addCriterion("analyseFlag in", values, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagNotIn(List<Integer> values) {
            addCriterion("analyseFlag not in", values, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagBetween(Integer value1, Integer value2) {
            addCriterion("analyseFlag between", value1, value2, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andAnalyseFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("analyseFlag not between", value1, value2, "analyseFlag");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("startTime is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("startTime is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(String value) {
            addCriterion("startTime =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("startTime <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(String value) {
            addCriterion("startTime >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("startTime >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(String value) {
            addCriterion("startTime <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("startTime <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLike(String value) {
            addCriterion("startTime like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotLike(String value) {
            addCriterion("startTime not like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<String> values) {
            addCriterion("startTime in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("startTime not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("startTime between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("startTime not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("endTime is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("endTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(String value) {
            addCriterion("endTime =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("endTime <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(String value) {
            addCriterion("endTime >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("endTime >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(String value) {
            addCriterion("endTime <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("endTime <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLike(String value) {
            addCriterion("endTime like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotLike(String value) {
            addCriterion("endTime not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<String> values) {
            addCriterion("endTime in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("endTime not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("endTime between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("endTime not between", value1, value2, "endTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_monthAccount
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 12 10:55:08 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_monthAccount
     *
     * @mbggenerated Thu Nov 12 10:55:08 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}